name: Docker build

on:
  workflow_call:
    inputs:
      push:
        default: false
        required: false
        type: boolean
      version:
        default: latest
        type: string
        required: false
    secrets:
      docker_username:
        required: true
      docker_token:
        required: true
      nexus_username:
        required: true
      nexus_token:
        required: true
      security_checks_token:
        required: true

jobs:
  release-docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Build Cache
        id: restore-build-cache
        uses: actions/cache/restore@v3
        with:
          path: ./dist
          key: ${{ runner.os }}-${{ github.sha }}-build

      - name: Fail on absent cache
        if: steps.restore-build-cache.outputs.cache-hit != 'true'
        run: exit 1

      - name: Configure docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            docker.io/microlc/middleware
            nexus.mia-platform.eu/microlc/middleware
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}

      - name: Login to Mia registry
        uses: docker/login-action@v3
        with:
          registry: nexus.mia-platform.eu
          username: ${{ secrets.nexus_username }}
          password: ${{ secrets.nexus_token }}

      - name: Build and push
        if: ${{ inputs.push }}
        uses: docker/build-push-action@v5
        with:
          context: .
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=${{ steps.meta.outputs.tags }}
          cache-to: type=inline
  
  security-checks:
    needs:
      - release-docker
    name: Triggers security checks
    runs-on: ubuntu-latest

    steps:
      - name: Invoke API
        if: ${{ inputs.push }}
        run: |
          curl --request POST \
            --form token=${{ secrets.security_checks_token }} \
            --form ref=main \
            --form "variables[VERSION]=${{ inputs.version }}" \
            "https://git.tools.mia-platform.eu/api/v4/projects/86269/trigger/pipeline"
