name: PR on Main

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        node-version:
         - 16.x
         - 17.x
         - 18.x
    uses: micro-lc/middleware/.github/workflows/tests.yml@main
    with:
      node-version: ${{ matrix.node-version }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  lint:
    uses: micro-lc/middleware/.github/workflows/lint.yml@main

  build:
    uses: micro-lc/middleware/.github/workflows/build.yml@main
